# This is a GitHub Actions workflow file to test the DevDraft Action.
name: Test DevDraft Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run DevDraft Action
        uses: ./
        with:
          ticketId: "JIRA-001"
          title: "Add login button"
          description: "We need a login button in the header."