# This is a GitHub Actions workflow file to test the DevDraft Action.
name: Test DevDraft Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Run DevDraft Action
        uses: ./
        with:
          ticketId: "JIRA-001"
          description: "We need a counter that start from 0 and increments by 1 every second. Implement using HTML, CSS, and JavaScript."
          issueType: "feature"
          issueSummary: "add-counter-component"